//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ideassoccer.BaseStation.UI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.5.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4991")]
        public int Robot1UdpPort {
            get {
                return ((int)(this["Robot1UdpPort"]));
            }
            set {
                this["Robot1UdpPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Robot 1")]
        public string Robot1Name {
            get {
                return ((string)(this["Robot1Name"]));
            }
            set {
                this["Robot1Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string Robot1Id {
            get {
                return ((string)(this["Robot1Id"]));
            }
            set {
                this["Robot1Id"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.0.100")]
        public string Robot1EndpointAddress {
            get {
                return ((string)(this["Robot1EndpointAddress"]));
            }
            set {
                this["Robot1EndpointAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4242")]
        public int Robot1EndpointPort {
            get {
                return ((int)(this["Robot1EndpointPort"]));
            }
            set {
                this["Robot1EndpointPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public string Robot2Id {
            get {
                return ((string)(this["Robot2Id"]));
            }
            set {
                this["Robot2Id"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Robot 2")]
        public string Robot2Name {
            get {
                return ((string)(this["Robot2Name"]));
            }
            set {
                this["Robot2Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4992")]
        public int Robot2UdpPort {
            get {
                return ((int)(this["Robot2UdpPort"]));
            }
            set {
                this["Robot2UdpPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.0.103")]
        public string Robot2EndpointAddress {
            get {
                return ((string)(this["Robot2EndpointAddress"]));
            }
            set {
                this["Robot2EndpointAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4242")]
        public int Robot2EndpointPort {
            get {
                return ((int)(this["Robot2EndpointPort"]));
            }
            set {
                this["Robot2EndpointPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("127.0.0.1:9000")]
        public string RefBoxEndPoint {
            get {
                return ((string)(this["RefBoxEndPoint"]));
            }
            set {
                this["RefBoxEndPoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("gk")]
        public string RobotGKId {
            get {
                return ((string)(this["RobotGKId"]));
            }
            set {
                this["RobotGKId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Robot Kiper")]
        public string RobotGKName {
            get {
                return ((string)(this["RobotGKName"]));
            }
            set {
                this["RobotGKName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4990")]
        public int RobotGKUdpPort {
            get {
                return ((int)(this["RobotGKUdpPort"]));
            }
            set {
                this["RobotGKUdpPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.0.108")]
        public string RobotGKEndpointAddress {
            get {
                return ((string)(this["RobotGKEndpointAddress"]));
            }
            set {
                this["RobotGKEndpointAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4242")]
        public int RobotGKEndpointPort {
            get {
                return ((int)(this["RobotGKEndpointPort"]));
            }
            set {
                this["RobotGKEndpointPort"] = value;
            }
        }
    }
}
