name: Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: Release
    runs-on: windows-latest
    permissions:
      contents: write
    env:
      APP_VERSION: ${{ github.ref_name }}
      PROJECT_NAME: Ideassoccer.BaseStation.UI
      ARCHIVE_NAME: Ideassoccer.BaseStation.UI.zip
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'
      
    # Restore the application
    - name:  Restore dependencies
      run: dotnet restore

    # update version.txt based on tag name
    - name: Update version.txt
      run: echo ${{ github.ref_name }} > .\$env:PROJECT_NAME\version.txt

    # Build the Windows Application Packaging project
    - name: Publish
      env:
        Runtime: win-x64
        Configuration: Release
      run:
        $APP_VERSION = $env:APP_VERSION.Substring(1);
        dotnet publish `
          "$env:PROJECT_NAME/$env:PROJECT_NAME.csproj" `
          -r $env:Runtime `
          /p:Configuration=$env:Configuration `
          /p:PublishSingleFile=true  `
          /p:IncludeNativeLibrariesForSelfExtract=true  `
          /p:SelfContained=true  `
          /p:DebugType=None `
          /p:DebugSymbols=false `
          /p:Version=$APP_VERSION `
          /p:InformationalVersion=$env:APP_VERSION

    # Create release archive files (zip)
    - name: Create archive
      run: |
        Compress-Archive `
          -Path Ideassoccer.BaseStation.UI\bin\Release\net6.0-windows\win-x64\publish\* `
          -DestinationPath .\$env:ARCHIVE_NAME

    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        draft: true
        generate_release_notes: true
        files: $env:ARCHIVE_NAME

    - name: Push version.txt
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add $env:PROJECT_NAME/version.txt
        git commit -m "$env:APP_VERSION"
        git push